# Generated by Django 6.0.6 on 2026-07-06 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_delivery_time', models.PositiveIntegerField(default=30, help_text='Estimated OTP delivery time in seconds')),
                ('is_available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='countries.country')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='services.service')),
            ],
            options={
                'ordering': ['country', 'service'],
                'unique_together': {('country', 'service')},
            },
        ),
    ]
