# Generated by Django 6.0.6 on 2026-10-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Shown in the category info panel on the shop page'),
        ),
        migrations.AddField(
            model_name='logitem',
            name='email_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='logitem',
            name='recovery_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='logitem',
            name='two_fa',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='logproduct',
            name='format_labels',
            field=models.CharField(default='EMAIL | PASSWORD | EMAIL PASSWORD | 2FA | RECOVERY EMAIL', help_text='Pipe-separated format shown on the buy card, e.g. EMAIL | PASSWORD | 2FA', max_length=255),
        ),
        migrations.AddField(
            model_name='logpurchase',
            name='email_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='logpurchase',
            name='recovery_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='logpurchase',
            name='two_fa',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
