# Generated by Django 6.0.6 on 2026-10-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_logcategory_description_logitem_email_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logitem',
            old_name='username',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='logpurchase',
            old_name='username',
            new_name='uid',
        ),
        migrations.AlterField(
            model_name='logproduct',
            name='format_labels',
            field=models.CharField(default='UID | PASSWORD | EMAIL PASSWORD | 2FA | RECOVERY EMAIL', help_text='Pipe-separated format shown on the buy card', max_length=255),
        ),
    ]
