# Generated by Django 6.0.6 on 2026-10-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_rename_username_logitem_uid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logproduct',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log Group', 'verbose_name_plural': 'Log Groups'},
        ),
    ]
