# Generated by Django 6.0.6 on 2026-10-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_logproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpurchase',
            name='format_labels',
            field=models.CharField(default='UID | PASSWORD | EMAIL PASSWORD | 2FA | RECOVERY EMAIL', help_text='Format of the log group at time of purchase', max_length=255),
        ),
    ]
