# Generated by Django 6.0.6 on 2026-10-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_logpurchase_format_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpurchase',
            name='product_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
