# Generated by Django 6.0.6 on 2026-07-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='provider_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
