# Generated by Django 6.0.6 on 2026-07-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_provider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
