# Generated by Django 6.0.6 on 2026-07-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_alter_country_iso_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='server',
            field=models.CharField(choices=[('server1', 'Server 1'), ('server2', 'Server 2'), ('server3', 'Server 3')], default='server3', max_length=20),
        ),
    ]
