# Generated by Django 6.0.6 on 2026-07-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_country_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='provider_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
