# Generated by Django 6.0.6 on 2026-07-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_alter_country_iso_code_alter_country_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='country',
            unique_together={('name', 'server')},
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='country',
            unique_together={('iso_code', 'server'), ('name', 'server')},
        ),
    ]
