# Generated by Django 6.0.6 on 2026-07-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='provider_id',
            field=models.PositiveIntegerField(blank=True, help_text='InstantNums Provider Service ID', null=True, unique=True),
        ),
    ]
