# Generated by Django 6.0.6 on 2026-07-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_provider_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='code',
        ),
    ]
