# Generated by Django 6.0.6 on 2026-07-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='provider_id',
            field=models.PositiveIntegerField(blank=True, help_text='Provider Service ID', null=True, unique=True),
        ),
    ]
