# Generated by Django 6.0.6 on 2026-07-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_provider_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.CharField(blank=True, help_text='Provider service code (e.g., am, fb, ig for DaisySMS)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='provider_id',
            field=models.PositiveIntegerField(blank=True, help_text='Provider Service ID (for InstantNums numeric IDs)', null=True, unique=True),
        ),
    ]
