# Generated by Django 6.0.6 on 2026-09-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
