# Generated by Django 6.0.6 on 2026-09-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_transaction_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='virtual_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='virtual_account_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='virtual_bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
