# Generated by Django 6.0.6 on 2026-07-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.CharField(default='InstantNums', max_length=50),
        ),
    ]
