# Generated by Django 6.0.6 on 2026-07-21 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_full_sms_order_sms_received_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='refund_processed',
        ),
    ]
